### ISSUE TITLE
Configurable chunk size

### ISSUE THREAD

**Issue by git-masoud** [eclipse-edc/Technology-Aws#112]
# Feature Request

Currently, the chunk size in the data sink is hard-coded to 500MB as CHUNK_SIZE_IN_BYTES. This could limit users in particularl environments with constrained memory resources.
We propose making the chunk size configurable via the EDC configuration.

## Which Areas Would Be Affected?
S3-Dataplane-extension , S3-Datasink

## Why Is the Feature Desired?
When edc is being deployed in an environment which has limited memory size 500mb chunk size is too much and dataplane cannot transfer a large size file

## Solution Proposal
Get the value from configuration , and after validation pass it to the datasink.

**Comment by ndr-brt** [comment]
thanks, could you take care of this? eventually I will assign the issue to you
