### ISSUE TITLE
Any S3 Transfer Failure causes failures in subsequent transfers due to connection pool shutdown

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-edc/Technology-Aws#244]
# Bug Report

## Describe the Bug
- Any failure during S3 Tansfer causes subsequent requests to fail due to error: `Connection pool shut down`

_A clear and concise description of the bug._

### Expected Behavior

_A clear and concise description of what you expected to happen._
- If one S3 transfer fails, subsequent request should work fine. 

### Observed Behavior

_A clear and concise description of what happened instead._

## Steps to Reproduce

1. Initiate a transfer with an non existing destination bucket.
```json
{
  "@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/"
  },
  "assetId": "30",
  "connectorAddress": "http://alice-controlplane:8084/api/v1/dsp",
  "connectorId": "BPNL000000000001",
  "contractId": "26615fbd-e474-40ce-aff4-a2da04b6e6ca",
  "dataDestination": {
    "type": "AmazonS3",
    "keyName": "alice-test-document.txt",
    "bucketName": "this-bucket-does-not-exist",
    "region": "us-east-1",
    "endpointOverride": "http://bob-minio:9000",
    "accessKeyId": "bobawsclient",
    "secretAccessKey": "bobawssecret"
  },
  "protocol": "dataspace-protocol-http"
}
```
2. Get Transfer State. It should be `TERMINATED`
3. Initiate another transfer this time with a bucket which already exists.
4. Get Transfer State. It should be `TERMINATED`. 

Provider DataPlane Stack Trace:
```
DEBUG 2024-02-27T09:12:05.38690007 Transferring from AmazonS3 to AmazonS3.
SEVERE 2024-02-27T09:12:05.659398427 Failed to download the alice-test-document.txt object: Connection pool shut down
org.eclipse.edc.connector.dataplane.aws.s3.exceptions.S3DataSourceException: Connection pool shut down
	at org.eclipse.edc.connector.dataplane.aws.s3.S3DataSource$S3Part.openStream(S3DataSource.java:130)
	at org.eclipse.edc.connector.dataplane.aws.s3.S3DataSink.transferParts(S3DataSink.java:50)
	at org.eclipse.edc.connector.dataplane.util.sink.ParallelSink.lambda$transfer$3(ParallelSink.java:82)
```

## Context Information

_Add any other context about the problem here._

- Used latest EDC version (0.6.0) but this bug existed in earlier version as well `0.5.3`.

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by paullatzelsperger** [comment]
un-assigned myself due to a lack of bandwidth
