### ISSUE TITLE
AWS Secrets Management Vault doesn't update existing secrets

### ISSUE THREAD

**Issue by rafaelmag110** [eclipse-edc/Technology-Aws#373]
# Bug Report

## Describe the Bug

The current implemention of the AWS Vault storeSecret method does not update an existing secret.
This behavior is unexpected, as other implementations Vault interface (such as the hashicorp vault) do update the secret.

This unexpected behavior also breaks the current functioning of the EDR cache, since it needs to update the underlying secret when an EDR is refreshed.

**Comment by zub4t** [comment]
Can I have this issue ?  @ndr-brt  @rafaelmag110
